# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[
        ('libmpv-2.dll', '.'),
        ('mpv.exe', '.'),
        ('ffmpeg/ffmpeg.exe', 'ffmpeg'),
        ('ffmpeg/ffprobe.exe', 'ffmpeg'),
        ('ffmpeg/bin/ffmpeg.exe', 'ffmpeg'),
        ('ffmpeg/bin/ffprobe.exe', 'ffmpeg'),
        ('ffmpeg/bin/ffplay.exe', 'ffmpeg'),
    ],
    datas=[
        ('icon.ico', '.'),
        ('chevron-down.png', '.'),
        ('Whisper', 'whisper'),
        ('ffmpeg/presets', 'ffmpeg/presets'),
        ('ffmpeg/doc', 'ffmpeg/doc'),
        ('ffmpeg/LICENSE', 'ffmpeg'),
        ('ffmpeg/README.txt', 'ffmpeg'),
        ('D:\\SUBTV\\Version 4 packing\\.venv\\lib\\site-packages\\faster_whisper\\assets', 'faster_whisper/assets'),
    ],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui', 
        'PyQt6.QtWidgets',
        'qtawesome',
        'mpv',
        'faster_whisper',
        'easynmt',
        'easynmt.models',
        'easynmt.models.opus_mt',
        'easynmt.models.mbart50',
        'easynmt.models.m2m_100',
        'easynmt.util',
        'easynmt.laserembeddings',
        'huggingface_hub',
        'onnxruntime',
        'nltk',
        'torch',
        'transformers',
        'tokenizers',
        'sentencepiece',
        'sacremoses',
        'fasttext',
        'numpy',
        'scipy',
        'sklearn',
        'PIL',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'tqdm',
        'packaging',
        'filelock',
        'typing_extensions',
        'regex',
        'pyyaml',
        'click',
        'joblib',
        'threadpoolctl',
        'av',
        'ctranslate2',
        'onnxruntime.capi.onnxruntime_pybind11_state',
        'onnxruntime.capi._pybind_state',
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'pandas',
        'jupyter',
        'IPython',
        'notebook',
        'sphinx',
        'pytest',
        'setuptools',
        'distutils',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Zest Sync Player',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
    version='version_info.txt',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Zest Sync Player'
)